name: picture_in_picture
description: Pluguin para gerenciamento de PIP Mode em aplicativos Flutter.
version: 0.0.2
homepage: "https://www.omnisaude.co/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter_modular: ^2.0.1

  flutter:
    sdk: flutter

flutter_localizations:
  sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.12

  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/shared/logo/appstore.png'
  image_path_android: 'assets/shared/logo/playstore.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/avatar/
    - assets/shared/

  plugin:
    platforms:
      android:
        package: com.leobidoous.omnisaude.picture_in_picture
        pluginClass: PictureInPicturePlugin
      ios:
        pluginClass: PictureInPicturePlugin

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
